#!/bin/bash

optstring=":n:a:d:l"
FJ_HOME="$HOME/.config/firejail/"

while getopts ${optstring} arg; do
  CX_PROFILE_PATH="$FJ_HOME/$OPTARG.profile"
  case ${arg} in

    n)  
        [ -z "$3" ] && echo "Enter name of container" && exit 1

	    CX_NAME=$3

        echo "Creating a container for $OPTARG with name $CX_NAME..."

        touch $HOME/.config/firejail/$CX_NAME.profile
	    echo "include $CX_NAME.local" >> ~/.config/firejail/$CX_NAME.profile
        echo "include globals.local" >> ~/.config/firejail/$CX_NAME.profile
        echo "------------"

        echo "Successfully created container for $OPTARG"

        ;;
    a)
        [ -z "$3" ] && echo "Must supply a device/path as additional argument to -a" && exit 1
	    CX_DEVICE=$3

        # PERFORM CHECK TO SEE IF $3 and OPTARG is valid
        if [ -d $CX_DEVICE ]; then

	        WL_DEVICE="blacklist\ $CX_DEVICE"
	        WL_DEVICE=$(echo $WL_DEVICE | sed 's/\//\\\//g')
	        sed -i /"$WL_DEVICE"/d $CX_PROFILE_PATH
            echo " $OPTARG can now access $CX_DEVICE!"

        elif [ $CX_DEVICE == "webcam" ]; then
            WL_DEVICE="novideo"
	        sed -i /"$WL_DEVICE"/d $CX_PROFILE_PATH
            echo "$OPTARG can now access the webcam!"
        elif [ $CX_DEVICE == "mic" ]; then
            WL_DEVICE="nosound"
	        sed -i /"$WL_DEVICE"/d $CX_PROFILE_PATH
            echo "$OPTARG can now access the mic!"
        elif [ $CX_DEVICE == "net" ]; then
            WL_DEVICE="net none"
            echo $CX_PROFILE_PATH
	        sed -i /"$WL_DEVICE"/d $CX_PROFILE_PATH
            echo "$OPTARG can now access the internet!"
        fi
        ;;
    d)
        [ -z "$3" ] && echo "Enter a device to deny for $OPTARG" && exit 1
        # PERFORM CHECK TO SEE IF $3 and OPTARG is valid

	    CX_DEVICE=$3
        if [ -d $CX_DEVICE ]; then

            echo "blacklist $CX_DEVICE" >> $CX_PROFILE_PATH
            echo "$OPTARG has been denied access to $CX_DEVICE"

        elif [ $CX_DEVICE == "webcam" ]; then
                echo "novideo" >> $CX_PROFILE_PATH
                echo "$OPTARG has been denied access to the webcam"
        elif [ $CX_DEVICE == "mic" ]; then
                echo "nosound" >> $CX_PROFILE_PATH
                echo "$OPTARG has been denied access to the mic"
        elif [ $CX_DEVICE == "net" ]; then
                echo "net none" >> $CX_PROFILE_PATH
                echo "$OPTARG has been denied access to the internet"
        fi
        ;;
    l)
        echo "Listing all containers"
	    echo "-------"
	    ls -1 $HOME/.config/firejail/ | sed -e 's/\..*$//'
        ;;
    :)
        echo "$0: Must supply an argument to -$OPTARG." >&2
        exit 1
        ;;
    ?)
        echo "Invalid option: -${OPTARG}."
        exit 2
        ;;
    sudo firecfg
  esac
done